name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Or 'master', depending on your default branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # This allows the action to push to your repository
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # IMPORTANT: Point to the folder containing your website files
          publish_dir: ./
          # If your files are in a folder named 'public' or 'dist', change this to './public' or './dist'
